Repository nightwatchjs/nightwatch, pull requests merged in 2022-09, with the labels that each got.

#3353 Fix#3352 Custom command throwing TypeError while returning error
  lib/api/_loaders/command.js
  test/apidemos/custom-commands/testUsingCustomGetEmail.js
  test/extra/commands/es6async/getEmail.js
  test/src/apidemos/custom-commands/testCustomCommandsAsync.js
Labels: bug

#3367 Fix #3361 expect.cookie always returning undefined value
  lib/api/expect/cookie.js
  test/lib/nocks.js
Labels: bug, complexity: low, regression

#3362 pass desiredCapabilities if browser options are not present.
  lib/transport/selenium-webdriver/browserstack.js
  lib/transport/selenium-webdriver/mobile-webdriver.js
  test/src/core/testCreateSession.js
  test/src/index/transport/testBrowserstackTransport.js
Labels: bug, complexity: low
